-- 0057_missing_columns.sql

ALTER TABLE companies
  ADD COLUMN IF NOT EXISTS is_exchange_listed BOOLEAN DEFAULT false;

ALTER TABLE pol_states
  ADD COLUMN IF NOT EXISTS cond_prosperity INTEGER DEFAULT 50,
  ADD COLUMN IF NOT EXISTS cond_jobs INTEGER DEFAULT 50,
  ADD COLUMN IF NOT EXISTS cond_order INTEGER DEFAULT 50,
  ADD COLUMN IF NOT EXISTS cond_cohesion INTEGER DEFAULT 50,
  ADD COLUMN IF NOT EXISTS cond_budget INTEGER DEFAULT 50,
  ADD COLUMN IF NOT EXISTS cond_updated_arc INTEGER DEFAULT 0;
