-- UP
BEGIN;

ALTER TABLE pol_parties ADD COLUMN IF NOT EXISTS slogan VARCHAR(255);
ALTER TABLE pol_parties ADD COLUMN IF NOT EXISTS crisis_id VARCHAR(50);
ALTER TABLE pol_parties ADD COLUMN IF NOT EXISTS ideology_axes JSONB;
ALTER TABLE pol_parties ADD COLUMN IF NOT EXISTS manifesto_policies JSONB;
ALTER TABLE pol_parties ADD COLUMN IF NOT EXISTS founders JSONB DEFAULT '[]'::jsonb;

COMMIT;
